import { readdirSync, mkdirSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const galleryDir = join(__dirname, '..', 'public', 'gallery')
const outDir = join(__dirname, '..', 'src', 'generated')
const outFile = join(outDir, 'galleryCount.ts')

const numberedImage = /^\d+\.(jpg|jpeg|png|gif|webp)$/i

let count = 0
try {
  const files = readdirSync(galleryDir)
  count = files.filter((f) => numberedImage.test(f)).length
} catch {
  // public/gallery 없으면 0
}

mkdirSync(outDir, { recursive: true })
writeFileSync(
  outFile,
  `// Generated by scripts/count-gallery.mjs – do not edit manually
export const GALLERY_IMAGE_COUNT = ${count};
`,
  'utf8'
)
console.log(`Gallery: ${count} images → src/generated/galleryCount.ts`)
